#!/usr/bin/env bash
set -eo pipefail

MODULE=${1:-pwm}
SSH_HOST=${2:-zero.tvidal.uk}

cd "$PWD/`dirname $0`/.."

./gradlew :pwm:linkDebugExecutableArm \
    && scp -C "$PWD/$MODULE/build/bin/arm/debugExecutable/$MODULE.kexe" "pi@$SSH_HOST:~" \
    && ssh "pi@$SSH_HOST" 'sudo bash -' <<EOF

chown root:pi $MODULE.kexe;
chmod 04775 $MODULE.kexe;
./$MODULE.kexe $*
EOF

cd "$OLDPWD"
